name: Android CI with Gradle

on:
  push:
    branches: [ master develop]
  pull_request:
    branches: [ master develop]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: 1.8
    - name: Print Java version
      run: java -version
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run unit tests with Gradle
      run: ./gradlew opensrp-anc:clean opensrp-anc:jacocoTestReport --stacktrace
    - name: Generate Javadoc with Gradle
      run: ./gradlew javadoc
    - name: Upload coverage to Coveralls with Gradle
      run: ./gradlew opensrp-anc:coveralls --stacktrace

env:
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
